import os
from datetime import datetime

def generate_html_report(target, findings, output_path):
    """
    Generates a beautiful, professional HTML dashboard for scan results.
    """
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    # Calculate stats
    total = len(findings)
    critical = len([f for f in findings if f.get('severity') == 'CRITICAL'])
    high = len([f for f in findings if f.get('severity') == 'HIGH'])
    
    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Elengenix Scan Report - {target}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <style>
            body {{ background-color: #0f172a; color: #e2e8f0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }}
            .card {{ background-color: #1e293b; border: none; border-radius: 15px; margin-bottom: 20px; }}
            .header-banner {{ background: linear-gradient(90deg, #06b6d4, #3b82f6); padding: 40px 0; border-radius: 0 0 30px 30px; margin-bottom: 40px; }}
            .severity-critical {{ color: #ef4444; font-weight: bold; }}
            .severity-high {{ color: #f97316; font-weight: bold; }}
            .badge-critical {{ background-color: #ef4444; }}
            .badge-high {{ background-color: #f97316; }}
            .badge-medium {{ background-color: #eab308; }}
        </style>
    </head>
    <body>
        <div class="header-banner text-center">
            <h1 class="display-4 fw-bold">🛡️ ELENGENIX AI REPORT</h1>
            <p class="lead">Target: <span class="badge bg-dark">{target}</span></p>
            <p>Scan Date: {now}</p>
        </div>

        <div class="container">
            <div class="row text-center mb-4">
                <div class="col-md-4">
                    <div class="card p-3">
                        <h3>{{total}}</h3>
                        <p class="text-muted">Total Findings</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card p-3">
                        <h3 class="severity-critical">{{critical}}</h3>
                        <p class="text-muted">Critical</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card p-3">
                        <h3 class="severity-high">{{high}}</h3>
                        <p class="text-muted">High Severity</p>
                    </div>
                </div>
            </div>

            <div class="card p-4">
                <h2 class="mb-4">🔍 Detailed Vulnerabilities</h2>
                <table class="table table-dark table-hover">
                    <thead>
                        <tr>
                            <th>Finding</th>
                            <th>Severity</th>
                            <th>URL</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
    """
    
    if findings:
        for f in findings:
            sev_class = f"badge-{f.get('severity', 'low').lower()}"
            html_content += f"""
                <tr>
                    <td>{f.get('name')}</td>
                    <td><span class="badge {sev_class}">{f.get('severity')}</span></td>
                    <td><code>{f.get('url')}</code></td>
                    <td><span class="text-success">Vulnerable</span></td>
                </tr>
            """
    else:
        html_content += "<tr><td colspan='4' class='text-center'>No vulnerabilities found yet.</td></tr>"

    html_content += """
                    </tbody>
                </table>
            </div>
            
            <div class="footer text-center mt-5 mb-5 text-muted">
                <p>Generated by Elengenix AI Framework &copy; 2026</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    with open(output_path, "w") as f:
        f.write(html_content)
    return output_path
